spring:
  config:
    activate:
      on-profile: test

  redis:
    host: 127.0.0.1
    port: 6379

  datasource:
    hikari:
      maximum-pool-size: 30
      max-lifetime: 60000
      jdbc-url: 
      username: 
      password:
      connection-timeout: 5000
      pool-name: Spring-HikariPool

  jpa:
    generate-ddl: true
    hibernate:
      ddl-auto: create
      naming:
        implicit-strategy: org.springframework.boot.orm.jpa.hibernate.SpringImplicitNamingStrategy
        physical-strategy: org.springframework.boot.orm.jpa.hibernate.SpringPhysicalNamingStrategy
    properties:
      hibernate:
        format_sql: true
        default_batch_fetch_size: 100
        use_sql_comments: true
