server:
  port: 8080

spring:
  config:
    activate:
      on-profile: local

#logging:
#  file.name: ./PJT-web.log
#  level:
#    root: INFO
#    org.hibernate.SQL: debug
#    org.hibernate.type: trace

jwt:
  secret:
  route:
    authentication:
      path: auth
      refresh: refresh

sms:
  serviceid: 
  secretkey: 
  accesskey: 
