server:
  port: 8090
armeria:
  ports:
    - port: 8099
      protocols:
        - http
        - proxy

spring:
  profiles:
    active: local
    default: local
    include:
      - core-local
  mail:
    host: smtp.gmail.com
    port: 587
    username: 
    password: 
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true

sms:
  serviceid: ncp:sms:kr:282615511747:validation_sms
  secretkey: 
  accesskey: 
